POST http://localhost:5500/guides
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmZWVmYTM5M2U1MDEwOGUxYzRiYjQ2Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NTQ1OTU2NywiZXhwIjoxNjk1NTQ1OTY3fQ.LPX-0fT-7wTsertWstgwd26rMxeMuxfO5236LLThaIk

{
    "title": "title4",
    "content": "description4",
    "notify": true
}

###
GET http://localhost:5500/guides
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmZWVmYTM5M2U1MDEwOGUxYzRiYjQ2Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NTQ1OTU2NywiZXhwIjoxNjk1NTQ1OTY3fQ.LPX-0fT-7wTsertWstgwd26rMxeMuxfO5236LLThaIk


###
GET http://localhost:5500/guides/64ff1a71b67f787d1a0e45d2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmZWVmYTM5M2U1MDEwOGUxYzRiYjQ2Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NTQ1OTU2NywiZXhwIjoxNjk1NTQ1OTY3fQ.LPX-0fT-7wTsertWstgwd26rMxeMuxfO5236LLThaIk

###
PATCH http://localhost:5500/guides/64ff1a71b67f787d1a0e45d2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmZWVmYTM5M2U1MDEwOGUxYzRiYjQ2Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NTQ1OTU2NywiZXhwIjoxNjk1NTQ1OTY3fQ.LPX-0fT-7wTsertWstgwd26rMxeMuxfO5236LLThaIk

{
    "title" : "title5",
    "content": "description5",
    "notify": true
}