###
GET http://localhost:5500/user-guides
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmZWVmYTM5M2U1MDEwOGUxYzRiYjQ2Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NTQ1OTU2NywiZXhwIjoxNjk1NTQ1OTY3fQ.LPX-0fT-7wTsertWstgwd26rMxeMuxfO5236LLThaIk

###
POST http://localhost:5500/user-guides/6500b16b9cbbe40968803d2e/read
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmZWVmYTM5M2U1MDEwOGUxYzRiYjQ2Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NTQ1OTU2NywiZXhwIjoxNjk1NTQ1OTY3fQ.LPX-0fT-7wTsertWstgwd26rMxeMuxfO5236LLThaIk


###
POST http://localhost:5500/user-guides/bulk
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmZWVmYTM5M2U1MDEwOGUxYzRiYjQ2Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NTQ1OTU2NywiZXhwIjoxNjk1NTQ1OTY3fQ.LPX-0fT-7wTsertWstgwd26rMxeMuxfO5236LLThaIk

{
    "guide_id" : "6500ae58d44f48a77276538f",
     "user_ids":["64feefa393e50108e1c4bb46", "64fef0e3bd15fb1ebd346ccc"]
}
