
# User ro'yxatdan o'tish agar birinchi marta ro'xatdan o'tayotgan bo'lsangiz routedagi AuthGuardlarni o'chirib qo'ying!


POST http://localhost:5500/users
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmZWVmYTM5M2U1MDEwOGUxYzRiYjQ2Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NDUyMzIxNiwiZXhwIjoxNjk0NjA5NjE2fQ.Cn2qUIZ1RgU6KecwalDO29PSCS6YloRD6w9rMeNCgc4

{
    "first_name" : "Dilshod",
    "last_name" : "Karimov",
    "age": 19,
    "role" : "employee",
    "username" : "user3",
    "password" : "1234"
}

###
POST http://localhost:5500/users/login
Content-Type: application/json

{
    "username": "user3",
    "password":"1234"
}



###
Get http://localhost:5500/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjUwMGFiZjRkNDRmNDhhNzcyNzY1MzdhIiwicm9sZSI6ImVtcGxveWVlIn0sImlhdCI6MTY5NDU0Mjg3NCwiZXhwIjoxNjk0NjI5Mjc0fQ.3tAAEHdrmOdWJ3kcCpUv2-3isCPFnG052s1z3RUm934
###

Get http://localhost:5500/users 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmZWVmYTM5M2U1MDEwOGUxYzRiYjQ2Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NDUyMzIxNiwiZXhwIjoxNjk0NjA5NjE2fQ.Cn2qUIZ1RgU6KecwalDO29PSCS6YloRD6w9rMeNCgc4

###
Get http://localhost:5500/users/6500abf4d44f48a77276537a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjUwMGFiZjRkNDRmNDhhNzcyNzY1MzdhIiwicm9sZSI6ImVtcGxveWVlIn0sImlhdCI6MTY5NDU0Mjg3NCwiZXhwIjoxNjk0NjI5Mjc0fQ.3tAAEHdrmOdWJ3kcCpUv2-3isCPFnG052s1z3RUm934


###
PATCH http://localhost:5500/users/6500abf4d44f48a77276537a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmZWVmYTM5M2U1MDEwOGUxYzRiYjQ2Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NDUyMzIxNiwiZXhwIjoxNjk0NjA5NjE2fQ.Cn2qUIZ1RgU6KecwalDO29PSCS6YloRD6w9rMeNCgc4

{
    "first_name":"Ravshan",
    "last_name":"Gulov",
    "age": 22,
    "role": "employee",
    "username": "user3",
    "password": "1234"
}

###
PATCH http://localhost:5500/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmZWVmYTM5M2U1MDEwOGUxYzRiYjQ2Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NDUyMzIxNiwiZXhwIjoxNjk0NjA5NjE2fQ.Cn2qUIZ1RgU6KecwalDO29PSCS6YloRD6w9rMeNCgc4

{
    "first_name":"Begzod",
    "last_name":"Yunosov",
    "age": 22,
    "role": "admin",
    "username": "user",
    "password": "1234"
}

###
DELETE  http://localhost:5500/users/64f3225440967642522b3a1c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmMzIyNTQ0MDk2NzY0MjUyMmIzYTFjIiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NDE4MjE2NSwiZXhwIjoxNjk0MjY4NTY1fQ.4VXlNxkJ-jwpE18OVXb1irHICxUnwG33PAhWVr7JWTk
