
# User ro'yxatdan o'tish agar birinchi marta ro'xatdan o'tayotgan bo'lsangiz routedagi AuthGuardlarni o'chirib qo'ying!


POST http://localhost:5500/users
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmZWVmYTM5M2U1MDEwOGUxYzRiYjQ2Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NTQ1OTU2NywiZXhwIjoxNjk1NTQ1OTY3fQ.LPX-0fT-7wTsertWstgwd26rMxeMuxfO5236LLThaIk

{
    "first_name" : "Faruh",
    "last_name" : "Fayziyev",
    "age": 28,
    "role" : "admin",
    "username" : "user4",
    "password" : "1234"
}

###
POST http://localhost:5500/users/login
Content-Type: application/json

{
    "username": "user",
    "password":"1234"
}



###
Get http://localhost:5500/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmZWVmYTM5M2U1MDEwOGUxYzRiYjQ2Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NTQ1OTU2NywiZXhwIjoxNjk1NTQ1OTY3fQ.LPX-0fT-7wTsertWstgwd26rMxeMuxfO5236LLThaIk
###

Get http://localhost:5500/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmZWVmYTM5M2U1MDEwOGUxYzRiYjQ2Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NTQ1OTU2NywiZXhwIjoxNjk1NTQ1OTY3fQ.LPX-0fT-7wTsertWstgwd26rMxeMuxfO5236LLThaIk

###
Get http://localhost:5500/users/650ea9114e7a9d37d6c0db74
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmZWVmYTM5M2U1MDEwOGUxYzRiYjQ2Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NTQ1OTU2NywiZXhwIjoxNjk1NTQ1OTY3fQ.LPX-0fT-7wTsertWstgwd26rMxeMuxfO5236LLThaIk


###
PATCH http://localhost:5500/users/650ea9114e7a9d37d6c0db74
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmZWVmYTM5M2U1MDEwOGUxYzRiYjQ2Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NTQ1OTU2NywiZXhwIjoxNjk1NTQ1OTY3fQ.LPX-0fT-7wTsertWstgwd26rMxeMuxfO5236LLThaIk

{
    "first_name":"Farux",
    "last_name":"Fayziyev",
    "age": 24,
    "role": "admin",
    "username": "user4",
    "password": "1234"
}

###
PATCH http://localhost:5500/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmZWVmYTM5M2U1MDEwOGUxYzRiYjQ2Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NTQ1OTU2NywiZXhwIjoxNjk1NTQ1OTY3fQ.LPX-0fT-7wTsertWstgwd26rMxeMuxfO5236LLThaIk

{
    "first_name":"Soxib",
    "last_name":"Amonov",
    "age": 22,
    "role": "admin",
    "username": "user",
    "password": "1234"
}

###
DELETE  http://localhost:5500/users/64fef0e3bd15fb1ebd346ccc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRmZWVmYTM5M2U1MDEwOGUxYzRiYjQ2Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NTQ1OTU2NywiZXhwIjoxNjk1NTQ1OTY3fQ.LPX-0fT-7wTsertWstgwd26rMxeMuxfO5236LLThaIk
